create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, seller_id int8, primary key (id));
create table tb_sellers (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_sales add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (seller_id) references tb_sellers;



postgres://
otgzhknyvkguis : 4b1a66ac552dffa9edac9b64337aa269fc5687465c25aa063ad63c7b99ccea17 @ ec2-54-224-120-186.compute-1.amazonaws.com:5432 / d9at46rf0iqv6e